[package]
name = "libra-builder"
description = "A custom builder for LLVM and LIBRA"
version = "0.1.0"
authors = ["Meng Xu <meng.xu.cs@uwaterloo.ca>"]
license = "GPL-3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
log = "0.4.20"
structopt = "0.3.26"
libra-shared = { path = "../shared" }
