[package]
name = "libra-testsuite"
description = "Testsuite for LIBRA components"
version = "0.1.0"
authors = ["Meng Xu <meng.xu.cs@uwaterloo.ca>"]
license = "GPL-3.0"
edition = "2021"

[build-dependencies]
libra-builder = { path = "../builder" }
libra-shared = { path = "../shared" }

[dependencies]
anyhow = "1.0.75"
fs_extra = "1.3.0"
log = "0.4.20"
rayon = "1.7.0"
serde = "1.0.188"
serde_json = "1.0.105"
structopt = "0.3.26"
tempfile = "3.8.0"
walkdir = "2.3.3"
libra-builder = { path = "../builder" }
libra-engine = { path = "../engine" }
libra-shared = { path = "../shared" }
